apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/ollu/infra/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
