apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: ">=4.13.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      admissionWebhooks:
        enabled: true
      service:
        type: NodePort
        enableHttp: false
        nodePorts:
          https: 30443
      extraArgs:
        default-ssl-certificate: "ingress-nginx/ingress-default-cert"
